### ISSUE TITLE
Center cards in their expansion panels

### ISSUE THREAD

**Issue by ChadChapman** [CodeTacoma/TacomaTechAPIFront#10]
Currently cards displaying in the expansion panels are left-aligned so if the card is not very wide, the asymmetrical white space looks "off".  Text inside card should remain left-justified but the card itself should be centered in its parent component.

**Comment by GavinThomas1192** [comment]
https://github.com/CodeTacoma/TacomaTechAPIFront/pull/16/commits/9d1ddc5f0fcf0c8e5fd379d5edae64f31a63d208

Grid, we can change it how we want now.
