### ISSUE TITLE
Map button

### ISSUE THREAD

**Issue by ChadChapman** [CodeTacoma/TacomaTechAPIFront#14]
Implement the Map button on cards that contain them, education cards for sure do.  Google Maps now charges for their API I think so may need to find an alternate solution.  Maybe a static map for some of them?

**Comment by GavinThomas1192** [comment]
If you'd like to have it completely free, we can hash together a url based on an address and open a new tab on google maps. Heres an example for sitecrafting. 
https://www.google.com/maps/place/2716+A+St,+Tacoma,+WA+98402/@47.236554,-122.4358153,

**Comment by GavinThomas1192** [comment]
@ChadChapman Can you link you're backend that your using for api root, I can add some address' to the data in order to make this google maps hack work.

**Comment by ChadChapman** [comment]
Yes, it's the same project you fixed a couple of weeks ago, pretty sure
it's called TacomaTechEco and I think it's under my profile

**Comment by ChadChapman** [comment]
Basically I just copied the React code it had under /api-frontend and put
that into the React repo we are on right now

**Comment by ChadChapman** [comment]
I'm at the Rainier game right now, I have no idea if these messages are
making it, lol

**Comment by GavinThomas1192** [comment]
https://github.com/CodeTacoma/TacomaTechAPIFront/commit/a0427d030fd3e3c8b221d0f699f5d2d368a93fb4
