### ISSUE TITLE
refactor end point root url

### ISSUE THREAD

**Issue by ChadChapman** [CodeTacoma/TacomaTechAPIFront#5]
The end point URL is currently hard-coded in App.js.  Should be set to a config var instead.

**Comment by GavinThomas1192** [comment]
I can do this next, keep in mind the actions I setup are based on the endpoint strings and will need to change accordingly when the api changes.

**Comment by GavinThomas1192** [comment]
https://github.com/CodeTacoma/TacomaTechAPIFront/pull/17
