### ISSUE TITLE
Styling fix for mobile or smaller screens

### ISSUE THREAD

**Issue by ChadChapman** [CodeTacoma/TacomaTechAPIFront#8]
Currently displays fine on full size screens but mobile and smaller screens the the info components are smooshed, text runs outside the elements, basically needs a css refactor for smaller screens.

**Comment by GavinThomas1192** [comment]
Mobile friendly is a never ending game, its good enough for now. I setup grid so it should scale to <150px. 
https://github.com/CodeTacoma/TacomaTechAPIFront/pull/16/commits/9d1ddc5f0fcf0c8e5fd379d5edae64f31a63d208
![screen shot 2018-08-06 at 9 02 28 pm](https://user-images.githubusercontent.com/28162527/43753749-237840b6-99bc-11e8-94c9-a608682e326a.png)
![screen shot 2018-08-06 at 9 02 42 pm](https://user-images.githubusercontent.com/28162527/43753754-27ed75f8-99bc-11e8-8088-b988414cde5e.png)
